export const ROUTES = {
  home: "/",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  authCallback: "/auth/callback",
  dashboard: "/dashboard",
  dashboardCreate: "/dashboard/create",
  dashboardFolders: "/dashboard/folders",
  dashboardHistory: "/dashboard/history",
  dashboardShared: "/dashboard/shared",
  dashboardCredits: "/dashboard/credits",
  dashboardProfile: "/dashboard/profile",
  admin: "/admin",
  adminTeachers: "/admin/teachers",
  adminEmployees: "/admin/employees",
  adminRoles: "/admin/roles",
  adminLessons: "/admin/lessons",
  adminCreditPackages: "/admin/credit-packages",
  adminAuditLogs: "/admin/audit-logs",
  adminGenerationEvents: "/admin/generation-events",
  adminTemplates: "/admin/templates",
  adminSchema: "/admin/schema",
  adminSettings: "/admin/settings",
  adminProfile: "/admin/profile",
  unauthorized: "/unauthorized",
} as const;
